In [23]:
import pandas as pd
import numpy as np

In [24]:
teste = pd.read_excel("../data/RAW/FIDC_RAM_2024_12_01.xlsx")

teste

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FIDC RAM
1,NaN,Item,2021-07-31 00:00:00,2021-08-31 00:00:00,2021-09-30 00:00:00,2021-10-31 00:00:00,2021-11-30 00:00:00,2021-12-31 00:00:00,2022-01-31 00:00:00,2022-02-28 00:00:00,...,2024-03-28 00:00:00,2024-04-30 00:00:00,2024-05-31 00:00:00,2024-06-28 00:00:00,2024-07-31 00:00:00,2024-08-30 00:00:00,2024-09-30 00:00:00,2024-10-31 00:00:00,2024-11-29 00:00:00,2024-12-31 00:00:00
2,NaN,PL Total,33178879.19,34224445.08,48866530.61,51703994.31,57564004.29,63056936.39,67015824.12,67894958.93,...,20233258.01,17114985.51,15288294.35,10896580.09,8004390.09,19182048.07,16633472.61,16904268.46,16973147.04,16626563.25
3,NaN,PL Sênior,0,0,3633824.06,4689739.44,4735225.5,6301995.54,9378377.74,9482864.57,...,11929199.54,10144843.43,8216241.64,6234417.26,4211948.32,11152016.52,9126965.37,9246718.6,9349170.86,9349170.86
4,NaN,PL Mezanino,0,0,4220641.21,5615676.51,5675521.78,8788036.61,8896651.2,9003877.22,...,0,0,0,0,0,0,0,0,0,0
5,NaN,PL Subordinada Jr.,33178879.19,34224445.08,41012065.34,41398578.36,47153257.01,47966904.24,48740795.18,49408217.14,...,8304058.47,6970142.08,7072052.71,4662162.83,3792441.77,8030031.55,7506507.24,7657549.86,7623976.18,7277392.39
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Rentabilidade Subordinada,0.013738,0.012943,0.013119,0.011198,0.013265,0.017255,0.016134,0.013693,...,0.019798,0.02,0.012367,0.012741,0.024236,0.020379,0.01575,0.020121,-0.004384,-0.045459
8,NaN,Rentabilidade Subordinada Junior (%CDI),5.314274,3.051674,2.993616,2.330975,2.260751,2.259889,2.203265,1.826804,...,2.37557,2.253775,1.484063,1.616263,2.671811,2.349164,1.888036,2.168445,-0.554165,-4.899655
9,NaN,Subordinação Junior,1,1,0.839267,0.800684,0.819145,0.760692,0.727303,0.727716,...,0.410416,0.407254,0.46258,0.427856,0.473795,0.418622,0.451289,0.452995,0.449179,0.437697
10,NaN,Subordinação Mezanino,0,0,0.086371,0.108612,0.098595,0.139367,0.132754,0.132615,...,0,0,0,0,0,0,0,0,0,0
11,NaN,Subordinação Total (Junior + Mezanino),1,1,0.925638,0.909296,0.91774,0.900059,0.860057,0.86033,...,0.410416,0.407254,0.46258,0.427856,0.473795,0.418622,0.451289,0.452995,0.449179,0.437697
12,NaN,Captação/Resgate Superiores,0,0,3619999.999961,0,0,1500000,3000000,0,...,-1912519,-1900903,-2017084.91,-2041197,-2112119,6887881,-2134389,0,0,0
13,NaN,Captação/Resgate Subordinada Mezanino,0,0,4200004.680573,1350000,0,3000000,0,0,...,0,0,0,0,0,0,0,0,0,0
14,NaN,Captação/Resgate Subordinada Junior,32778935.263318,613835,6299999.99998,1020000,5100000,0,0,0,...,-1400000,0,0,-2500000,-1000000,4100000,-650000,0,0,0
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Carteira (Direitos Creditórios),32453533.97,32650486.45,44947814.03,45498055.47,39544653.16,56113458.12,56486510.33,55681953.93,...,16331566.68,6916308.8,8006619.27,8581854.15,7817890.39,11806092.62,11476671.54,11668760.37,13135499.56,14256094.48
17,NaN,DC/PL(%),0.978138,0.954011,0.919808,0.879972,0.686968,0.889886,0.842883,0.820119,...,0.807164,0.404108,0.523709,0.787573,0.9767,0.615476,0.689974,0.690285,0.773899,0.857429
18,NaN,Caixa/Disponibilidades,91275.17,1625500.03,3197475,4511671.78,2177280.94,7029112.07,10937879.96,12290615.4,...,3957605.61,9965658.2,7333388.36,2402042.85,258884.0,7420615.5,5083845.19,5289766.87,4194130.53,3125371.93
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Vencidos,0,0,65292.9,142856.23,173900.65,0,635808.82,101263.18,...,0,0,0,45390,22330.93,0,0,0,12285.22,81293.21
21,NaN,Vencidos (% PL),0,0,0.001336,0.002763,0.003021,0,0.009487,0.001491,...,0,0,0,0.004166,0.00279,0,0,0,0.000724,0.004889
22,NaN,Vencidos - PDD (% PL),0,0,0.001336,0.002763,0.003021,0,0.009487,0.001491,...,0,0,0,0.004166,0.00279,0,0,0,-0.008911,-0.034652
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,PDD,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,163534.42,657439.89
25,NaN,PDD (% PL),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.009635,0.039542
26,NaN,PDD (% DC),0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0.01245,0.046116
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Ticket Médio,0,0,18511.739048,20029.811697,49539.267798,41315.627959,34959.57511,50215.43875,...,4916.678359,5360.467858,4312.082802,4995.373141,4884.717055,5119.734206,4236.706054,3841.45216,3880.922271,4215.811809
29,NaN,Prazo médio,0,0,22.655315,11.824905,78.684516,62.325784,47.425456,41.060731,...,21.252531,16.993629,21.999961,21.643164,19.145461,20.235431,20.349888,21.296334,24.719984,23.008381
30,NaN,Taxa Ponderada de Cessão,0,0,0.016687,0.018583,0.015726,0.015898,0.018129,0.021729,...,0.030169,0.032425,0.029158,0.027292,0.029426,0.029205,0.028229,0.031601,0.03272,0.029656
31,NaN,Taxa Ponderada de Cessão/CDI (%),0,0,3.807913,3.868232,2.680245,2.082081,2.475666,2.898867,...,3.619976,3.65396,3.49908,3.462097,3.244001,3.366545,3.383918,3.405673,4.136062,3.196391
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,CDI,0.002585,0.004241,0.004382,0.004804,0.005867,0.007635,0.007323,0.007496,...,0.008334,0.008874,0.008333,0.007883,0.009071,0.008675,0.008342,0.009279,0.007911,0.009278

In [25]:
df = teste.iloc[3:, 3:]

df

,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,...,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
3,0,3633824.06,4689739.44,4735225.5,6301995.54,9378377.74,9482864.57,9610542.39,10104573.4,13259501.29,...,11929199.54,10144843.43,8216241.64,6234417.26,4211948.32,11152016.52,9126965.37,9246718.6,9349170.86,9349170.86
4,0,4220641.21,5615676.51,5675521.78,8788036.61,8896651.2,9003877.22,9134627.71,11145466.78,12324352.64,...,0,0,0,0,0,0,0,0,0,0
5,34224445.08,41012065.34,41398578.36,47153257.01,47966904.24,48740795.18,49408217.14,50288369.61,51087129.72,45109495.52,...,8304058.47,6970142.08,7072052.71,4662162.83,3792441.77,8030031.55,7506507.24,7657549.86,7623976.18,7277392.39
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.012943,0.013119,0.011198,0.013265,0.017255,0.016134,0.013693,0.017814,0.015884,0.020012,...,0.019798,0.02,0.012367,0.012741,0.024236,0.020379,0.01575,0.020121,-0.004384,-0.045459
8,3.051674,2.993616,2.330975,2.260751,2.259889,2.203265,1.826804,1.929062,1.903765,1.940965,...,2.37557,2.253775,1.484063,1.616263,2.671811,2.349164,1.888036,2.168445,-0.554165,-4.899655
9,1,0.839267,0.800684,0.819145,0.760692,0.727303,0.727716,0.728463,0.706236,0.638101,...,0.410416,0.407254,0.46258,0.427856,0.473795,0.418622,0.451289,0.452995,0.449179,0.437697
10,0,0.086371,0.108612,0.098595,0.139367,0.132754,0.132615,0.132322,0.154077,0.174335,...,0,0,0,0,0,0,0,0,0,0
11,1,0.925638,0.909296,0.91774,0.900059,0.860057,0.86033,0.860784,0.860313,0.812436,...,0.410416,0.407254,0.46258,0.427856,0.473795,0.418622,0.451289,0.452995,0.449179,0.437697
12,0,3619999.999961,0,0,1500000,3000000,0,0,375000,3000000,...,-1912519,-1900903,-2017084.91,-2041197,-2112119,6887881,-2134389,0,0,0
13,0,4200004.680573,1350000,0,3000000,0,0,0,1875000,1000000,...,0,0,0,0,0,0,0,0,0,0
14,613835,6299999.99998,1020000,5100000,0,0,0,0,0,-7000000,...,-1400000,0,0,-2500000,-1000000,4100000,-650000,0,0,0
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,32650486.45,44947814.03,45498055.47,39544653.16,56113458.12,56486510.33,55681953.93,60084724.29,59722452.7,58375312.04,...,16331566.68,6916308.8,8006619.27,8581854.15,7817890.39,11806092.62,11476671.54,11668760.37,13135499.56,14256094.48
17,0.954011,0.919808,0.879972,0.686968,0.889886,0.842883,0.820119,0.87037,0.825612,0.825754,...,0.807164,0.404108,0.523709,0.787573,0.9767,0.615476,0.689974,0.690285,0.773899,0.857429
18,1625500.03,3197475,4511671.78,2177280.94,7029112.07,10937879.96,12290615.4,9048684.92,12696934.11,19393352.31,...,3957605.61,9965658.2,7333388.36,2402042.85,258884.0,7420615.5,5083845.19,5289766.87,4194130.53,3125371.93
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,0,65292.9,142856.23,173900.65,0,635808.82,101263.18,68631.1,238166.93,1224649.98,...,0,0,0,45390,22330.93,0,0,0,12285.22,81293.21
21,0,0.001336,0.002763,0.003021,0,0.009487,0.001491,0.000994,0.003292,0.017323,...,0,0,0,0.004166,0.00279,0,0,0,0.000724,0.004889
22,0,0.001336,0.002763,0.003021,0,0.009487,0.001491,0.000882,0.003292,0.017323,...,0,0,0,0.004166,0.00279,0,0,0,-0.008911,-0.034652
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,0,0,0,0,0,0,0,7769.54,0,0,...,0,0,0,0,0,0,0,0,163534.42,657439.89
25,0,0,0,0,0,0,0,0.000113,0,0,...,0,0,0,0,0,0,0,0,0.009635,0.039542
26,0,0,0,0,0,0,0,0.000129,0,0,...,0,0,0,0,0,0,0,0,0.01245,0.046116
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0,18511.739048,20029.811697,49539.267798,41315.627959,34959.57511,50215.43875,32645.43176,33044.854293,17996.89,...,4916.678359,5360.467858,4312.082802,4995.373141,4884.717055,5119.734206,4236.706054,3841.45216,3880.922271,4215.811809
29,0,22.655315,11.824905,78.684516,62.325784,47.425456,41.060731,28.880049,19.009213,20.363705,...,21.252531,16.993629,21.999961,21.643164,19.145461,20.235431,20.349888,21.296334,24.719984,23.008381
30,0,0.016687,0.018583,0.015726,0.015898,0.018129,0.021729,0.018688,0.018497,0.019838,...,0.030169,0.032425,0.029158,0.027292,0.029426,0.029205,0.028229,0.031601,0.03272,0.029656
31,0,3.807913,3.868232,2.680245,2.082081,2.475666,2.898867,2.023683,2.217012,1.924074,...,3.619976,3.65396,3.49908,3.462097,3.244001,3.366545,3.383918,3.405673,4.136062,3.196391
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,0.004241,0.004382,0.004804,0.005867,0.007635,0.007323,0.007496,0.009234,0.008343,0.01031,...,0.008334,0.008874,0.008333,0.007883,0.009071,0.008675,0.008342,0.009279,0.007911,0.009278

In [26]:
for col in df.columns:
    for idx, val in df[col].items():
        if isinstance(val, pd.NaT.__class__):  # somente NaT, não NaN
            print(f"NaT encontrado → Linha: {idx}, Coluna: '{col}', Valor: {val}")